version: '2.4'
services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "12348:5000"
    volumes:
      - planner_data:/app/data
      - planner_uploads:/app/app/static/uploads
    environment:
      - DATABASE_PATH=/app/data/planner.db
    dns:
      - 8.8.8.8
      - 1.1.1.1
volumes:
  planner_data:
  planner_uploads:
